--Kris Oud 301274712
--COMP 122 Sec 402 W23 

--Practice 1
CREATE TABLE W5P_SALESMEN (
    SALESMAN_ID NUMBER(5) PRIMARY KEY,
    S_NAME VARCHAR(30) NOT NULL,
    S_CITY VARCHAR(15),
    S_COMMISION NUMBER(5,2)
);

CREATE TABLE W5P_CUSTOMERS (
    CUSTOMER_ID NUMBER(5) PRIMARY KEY,
    CUST_NAME VARCHAR(30) NOT NULL,
    C_CITY VARCHAR(15),
    C_GRADE NUMBER(3),
    SALESMAN_ID NUMBER(5),
    CONSTRAINT FK_CUST2SALESMAN FOREIGN KEY (SALESMAN_ID) REFERENCES W5P_SALESMEN (SALESMAN_ID)
);

CREATE TABLE W5P_ORDERS (
    ORD_ID NUMBER(5) PRIMARY KEY,
    PURCH_AMT NUMBER(8,2),
    ORD_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_ID NUMBER(5),
    SALESMAN_ID NUMBER(5),
    CONSTRAINT ORD_CUST_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES W5P_CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT ORDSALES_FK FOREIGN KEY (SALESMAN_ID) REFERENCES W5P_SALESMEN (SALESMAN_ID)
);
--RAN INTO AN ISSUE WHERE IT SAID THIS CONSTRIANT ALREADY EXISTED BY THE NAME SO I HAD TO FIND SOMETHING NEW

INSERT INTO W5P_SALESMEN VALUES (1, 'Samford Slick', 'Scamsburg', 2.5);
INSERT INTO W5P_SALESMEN VALUES (2, 'Wanda Wrangler', 'Mass Newmarket', 1.5);
INSERT INTO W5P_CUSTOMERS VALUES (1, 'Marc DuMont', 'Spend Vegas', 1, 1);
INSERT INTO W5P_CUSTOMERS VALUES (2, 'Eb Aybuyer', 'Internets', 12, 2);
INSERT INTO W5P_ORDERS VALUES (1, 100.75, SYSDATE-3, 1, 2);
INSERT INTO W5P_ORDERS VALUES (2, 5200.12, SYSDATE, 2, 1);

SELECT * FROM w5p_customers;
SELECT * FROM w5p_salesmen;
SELECT * FROM w5p_orders;

--Practice 2

CREATE TABLE W5P_SALARY_GRADE (
    GRADE NUMBER(5) PRIMARY KEY,
    MIN_SALARY NUMBER(9,2) CHECK (MIN_SALARY > 0),
    MAX_SALARY NUMBER(9,2) CHECK (MAX_SALARY > 0)
);

--LEARNED YOU CANNOT SET RULES THAT RELY ON OTHER FIELDS (MAX_SALARY > MIN_SALARY)

CREATE TABLE W5P_DEPARTMENT (
    DEP_ID NUMBER(5) PRIMARY KEY,
    DEP_NAME VARCHAR(20) NOT NULL,
    DEP_LOCATION VARCHAR(15) NOT NULL
);

CREATE TABLE W5P_EMPLOYEES (
    EMP_ID NUMBER(5) PRIMARY KEY,
    EMP_NAME VARCHAR(15),
    JOB_NAME VARCHAR(10),
    MANAGER_ID NUMBER(5),
    HIRE_DATE DATE NOT NULL,
    SALARY NUMBER(10,2),
    COMMISSION NUMBER(7,2),
    DEP_ID NUMBER(5),
    CONSTRAINT FK_EMP_DEP FOREIGN KEY (DEP_ID) REFERENCES W5P_DEPARTMENT (DEP_ID)
);

INSERT INTO w5p_department VALUES (1, 'Database Penthouse', 'Hawaii');
INSERT INTO w5p_department VALUES (2, 'Sales Basement', 'Fargo');
INSERT INTO w5p_salary_grade VALUES (1, 50000.00, 70000.00);
INSERT INTO w5p_employees VALUES (1, 'Kris Oud', 'Nerd', '-9999', SYSDATE-365, 285000.07, 125.00, 1); 

SELECT * FROM w5p_department;
SELECT * FROM w5p_salary_grade;
SELECT * FROM w5p_employees;