--Practices for Subqieries: (Use JL_BOOKs XXXX)

--1. Determine how many books are in the Cooking category.
SELECT COUNT(*) FROM jl_books WHERE category='COOKING'

--2. Display the number of books with a retail price of more than $30.00.
SELECT COUNT(*) FROM jl_books WHERE retail > 30

--3. Display the most recent publication date of all books sold by JustLee Books.
SELECT title, pubdate 
FROM jl_books 
WHERE pubdate = (
    SELECT MAX(pubdate) 
    FROM jl_orderitems oi 
    JOIN jl_books b ON oi.isbn = b.isbn)

--4. Determine the total profit generated by sales to customer 1017. Note: Quantity should be
--reflected in the total profit calculation.

SELECT SUM(quantity * paideach) 
FROM jl_orderitems oi
JOIN jl_orders orders ON oi.order# = orders.order#
WHERE customer# = 1017

--5. List the retail price of the least expensive book in the Computer category.
SELECT title, retail 
FROM jl_books 
WHERE retail = (SELECT MIN(retail) FROM jl_books WHERE category = 'COMPUTER') 
AND category = 'COMPUTER'

--6. Determine the average profit generated by orders in the ORDERS table. Note: The total
--profit by order must be calculated before finding the average profit.
SELECT AVG(profit) FROM (SELECT retail - cost profit FROM jl_books)
